import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ToastProvider from "@/app/lib/toastify/toastify-provider";
import LoadingGlobalProvider from "./lib/loading/loading-provider";
import HighlightGlobalProvider from "./lib/highlight/highlight-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <LoadingGlobalProvider>
            <HighlightGlobalProvider>
              {children}
            </HighlightGlobalProvider>
          </LoadingGlobalProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
